version: '3'
services:
  # app:
  #   container_name: server
  #   build: .
  #   ports:
  #     - ${EXPOSE_PORT}:${PORT}
  #   restart: on-failure
  #   env_file:
  #     - .env
  #   depends_on:
  #     - database
  #     - cache
  #   environment:
  #     - DB_CONNECTION=${DB_HOST}:${DB_PORT}
  #     - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
  #     - WAIT_BEFORE_HOSTS=15
  #     - WAIT_SLEEP_INTERVAL=3
  #     - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}
  #   networks:
  #     - sfvn_test

  database:
    container_name: database
    ports:
      - 5435:5432
    image: postgis/postgis:13-master
    # volumes:
    #   - ../data/database:/var/lib/postgresql/data
    networks:
      - sfvn_test
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'A123bcd'
      POSTGRES_DB: 'sfvn_test_db'

  cache:
    image: redis/redis-stack-server
    restart: always
    ports:
      - '6381:6379'
    # command: redis-server --save 20 1 --loglevel warning
    # volumes: 
    #   - cache:/data

networks:
  sfvn_test:
    driver: bridge